### ISSUE TITLE
Make Metals version configurable

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals-eclipse#2]
It would be nice if it was possible to configure the Metals server version so that users could try out SNAPSHOT releases and new stable releases as soon as they're out. Currently, the version is hard coded in the source code

https://github.com/scalameta/metals-eclipse/blob/0a1547a8a33c7b23cc711c2107b28686ee67ab62/lsp-scala-plugin/src/main/scala/com/idiomaticsoft/lsp/scala/metals/MetalsLaunchConfigurationDelegate.scala#L30

In the VS Code plugin, there is a "Server Version" setting that allows users to provide a custom version

http://scalameta.org/metals/docs/editors/vscode.html#using-latest-metals-snapshot

Context: https://gitter.im/scalameta/metals?at=5d8bd31eb6aa4d6c90e13965

**Comment by mundacho** [comment]
Adding an option to configure is not hard. I just need some file, ideally online, where I can get the list of versions that the user can use.

**Comment by olafurpg** [comment]
I think it's best to let the user type in any string value and report an error when the resolution fails. This is what we do in the VS Code extension and it's working well, our CI publishes a SNAPSHOT release on every merge into master so the list of valid version numbers is always changing. Also, sometimes you want to try out a version of Metals that is locally published.
