### ISSUE TITLE
Cannot install in eclipse 2019-09

### ISSUE THREAD

**Issue by jcfandino** [scalameta/metals-eclipse#4]
Hi, I'm trying to install the plugin on a fresh eclipse 2019-09 installation.

Steps:
1. Add update site: `http://scalameta.org/metals-eclipse/update/`
2. Select "Scala LSP..."
3. Next

And I get this error:
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Scala LSP Plugin 0.1.0 (lsp.scala.feature.feature.group 0.1.0)
  Missing requirement: Scala LSP Plugin 0.1.0 (lsp.scala.feature.feature.group 0.1.0) requires 'org.eclipse.equinox.p2.iu; org.eclipse.lsp4e 0.12.0' but it could not be found
```
I looked for LSP4E in the eclipse update site and the version there is 0.10.0, do I need to use another update site?

**Comment by mundacho** [comment]
Yes, please use the latest LSP4e release update site at https://download.eclipse.org/lsp4e/releases/0.12.0/

**Comment by mundacho** [comment]
I added that info to the release notes. Next week I'll just update the repo to include all deps.

**Comment by jcfandino** [comment]
Awesome!
Thanks.
